name: Upload to test.pypi.org

on:
  # Triggers the workflow on push to the master branch
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installs and upgrades pip and the build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .[dev]

      - name: Build and Upload to PyPI
        continue-on-error: true
        run: |
          python3 -m build
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
